[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "http://lolli.cloud/*"
  to = "https://www.lolli.cloud/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.lolli.cloud/*"
  to = "https://www.lolli.cloud/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://daniele-lolli-uncledan-identity.netlify.app/*"
  to = "https://www.lolli.cloud/:splat"
  status = 301
  force = true
